Entity ::= String | Number | Identifier

String ::= '`' TODO '`'

Number ::= DecimalDigit+ | BinaryDigit+ 'b'

Identifier ::= Special (Special | DecimalDigit)*

BinaryDigit ::= '0' | '1'
DecimalDigit ::= '0' | '1' | ... | '9'
Special ::= '?' | '*' | '|'
